### ISSUE TITLE
Backpack Not Working?

### ISSUE THREAD

**Issue by Rezy774** [scotdotwtf/Final16#1]
is it made to be like that or is the a glitch?
![image](https://github.com/scotdotwtf/Final16/assets/128003302/06353a46-0aa9-4e8a-a731-e1f9b7103325)

**Comment by scotdotwtf** [comment]
Hello, recently I think my friend who works on the coregui, cola, fixed this. The reason it did that is because he didn’t implement backpack yet but I think he should have it now in the coregui.

**Comment by scotdotwtf** [comment]
Turns out it seems we havent implemented it yet, will work on that later! Thanks for the pull request.

**Comment by Rezy774** [comment]
welcome!
